/**
 * Mapping de marcas a sus logos
 */

export function getBrandLogo(brandName: string): string | null {
  const brandMap: Record<string, string> = {
    'Mahindra': 'https://www.mahindra.com//sites/default/files/2025-07/mahindra-red-logo.webp',
    'mahindra': 'https://www.mahindra.com//sites/default/files/2025-07/mahindra-red-logo.webp',
    'MAHINDRA': 'https://www.mahindra.com//sites/default/files/2025-07/mahindra-red-logo.webp',
    'Massey Ferguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'massey ferguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'MASSEY FERGUSON': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'MasseyFerguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'masseyferguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'Massey-Harris': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'massey-harris': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'MASSEY-HARRIS': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'McCormick': 'https://cdn.cookielaw.org/logos/4eea276a-8fd7-46af-9f86-8ace826b296b/0196d8f6-0d77-7a5b-afd9-5c88df82dba5/f10910ae-ff43-4aee-9519-1273c949c9c6/1_CPD_3-2-15.jpg',
    'mccormick': 'https://cdn.cookielaw.org/logos/4eea276a-8fd7-46af-9f86-8ace826b296b/0196d8f6-0d77-7a5b-afd9-5c88df82dba5/f10910ae-ff43-4aee-9519-1273c949c9c6/1_CPD_3-2-15.jpg',
    'MCCORMICK': 'https://cdn.cookielaw.org/logos/4eea276a-8fd7-46af-9f86-8ace826b296b/0196d8f6-0d77-7a5b-afd9-5c88df82dba5/f10910ae-ff43-4aee-9519-1273c949c9c6/1_CPD_3-2-15.jpg',
    'McCormick-Deering': 'https://cdn.cookielaw.org/logos/static/ot_company_logo.png',
    'mccormick-deering': 'https://cdn.cookielaw.org/logos/static/ot_company_logo.png',
    'MCCORMICK-DEERING': 'https://cdn.cookielaw.org/logos/static/ot_company_logo.png',
    'Advance-Rumely': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'advance-rumely': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'ADVANCE-RUMELY': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Allis Chalmers': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'allis chalmers': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'ALLIS CHALMERS': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'AllisChalmers': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Antonio': 'https://images.squarespace-cdn.com/content/v1/57aac7409f7456bea4405591/1476207017391-B0EXW9YH7D3EA7MY7XY8/New_ATO_Logo_Long.png?format=1000w',
    'antonio': 'https://images.squarespace-cdn.com/content/v1/57aac7409f7456bea4405591/1476207017391-B0EXW9YH7D3EA7MY7XY8/New_ATO_Logo_Long.png?format=1000w',
    'ANTONIO': 'https://images.squarespace-cdn.com/content/v1/57aac7409f7456bea4405591/1476207017391-B0EXW9YH7D3EA7MY7XY8/New_ATO_Logo_Long.png?format=1000w',
    'Avery': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'avery': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'AVERY': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Bobcat': 'https://res.cloudinary.com/doosan-bobcat/image/upload/c_pad,f_auto,h_600,q_auto,w_600/v1671465872/bobcat-assets/emea-approved/company/about-us/20221219-bobcat-properties-logo.jpg',
    'bobcat': 'https://res.cloudinary.com/doosan-bobcat/image/upload/c_pad,f_auto,h_600,q_auto,w_600/v1671465872/bobcat-assets/emea-approved/company/about-us/20221219-bobcat-properties-logo.jpg',
    'BOBCAT': 'https://res.cloudinary.com/doosan-bobcat/image/upload/c_pad,f_auto,h_600,q_auto,w_600/v1671465872/bobcat-assets/emea-approved/company/about-us/20221219-bobcat-properties-logo.jpg',
    'Bolinder-Munktell': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'bolinder-munktell': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'BOLINDER-MUNKTELL': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'Branson': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'branson': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'BRANSON': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'Bristol': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'bristol': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'BRISTOL': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Brockway': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'brockway': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'BROCKWAY': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Buhler': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'buhler': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'BUHLER': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Bukh': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'bukh': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'BUKH': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'C.O.D.': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'c.o.d.': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CBT': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cbt': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CNH': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cnh': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CO-OP': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'co-op': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Cabelas': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cabelas': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CABELAS': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Cameco': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cameco': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CAMECO': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Captain': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'captain': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CAPTAIN': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Carraro': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'carraro': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CARRARO': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Caterpillar': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'caterpillar': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'CATERPILLAR': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'Centaur': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'centaur': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CENTAUR': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Century': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'century': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'CENTURY': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Challenger': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'challenger': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'CHALLENGER': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Claas': 'https://www.claas.com/caas/v1/media/182446/data/420fa08f8ecd6a24f39953f300dc846a/landscape_ratio5x4/768/attachments-category-stage-image.webp',
    'claas': 'https://www.claas.com/caas/v1/media/182446/data/420fa08f8ecd6a24f39953f300dc846a/landscape_ratio5x4/768/attachments-category-stage-image.webp',
    'CLAAS': 'https://www.claas.com/caas/v1/media/182446/data/420fa08f8ecd6a24f39953f300dc846a/landscape_ratio5x4/768/attachments-category-stage-image.webp',
    'Cletrac': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cletrac': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CLETRAC': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Cockshutt': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'cockshutt': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'COCKSHUTT': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Coleman': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'coleman': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'COLEMAN': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Corbitt': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'corbitt': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CORBITT': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'County': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'county': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'COUNTY': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Cub': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'cub': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CUB': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Custom': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'custom': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'CUSTOM': 'https://www.gstatic.com/marketing-cms/assets/images/b3/a5/529a3d3047d18be9a5f3547ad7e3/google-logo-footer.svg',
    'Deutz': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'deutz': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'DEUTZ': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'Deutz-Fahr': 'https://www.deutz-fahr.com/media/thumbnails/Deutz-Fahr_SERVICE_Man-Work_DSC05224_CMYK_preview_thumb.jpg',
    'deutz-fahr': 'https://www.deutz-fahr.com/media/thumbnails/Deutz-Fahr_SERVICE_Man-Work_DSC05224_CMYK_preview_thumb.jpg',
    'DEUTZ-FAHR': 'https://www.deutz-fahr.com/media/thumbnails/Deutz-Fahr_SERVICE_Man-Work_DSC05224_CMYK_preview_thumb.jpg',
    'Ebro': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'ebro': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'EBRO': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'Erkunt': 'https://0da2a7bdd5.clvaw-cdnwnd.com/9723090a2d455758ee41978b4a4bd6d5/200000032-0db8a0db8d/70YilLogosu.png?ph=0da2a7bdd5',
    'erkunt': 'https://0da2a7bdd5.clvaw-cdnwnd.com/9723090a2d455758ee41978b4a4bd6d5/200000032-0db8a0db8d/70YilLogosu.png?ph=0da2a7bdd5',
    'ERKUNT': 'https://0da2a7bdd5.clvaw-cdnwnd.com/9723090a2d455758ee41978b4a4bd6d5/200000032-0db8a0db8d/70YilLogosu.png?ph=0da2a7bdd5',
    'Farm': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'farm': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'FARM': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Fendt': 'https://www.fendt.com/es/assets/media/layout/agco_logo.png',
    'fendt': 'https://www.fendt.com/es/assets/media/layout/agco_logo.png',
    'FENDT': 'https://www.fendt.com/es/assets/media/layout/agco_logo.png',
    'Ferguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'ferguson': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'FERGUSON': 'https://www.masseyferguson.com/content/dam/public/masseyfergusonglobal/markets/en/logos/icon-logo-agco-200x74.png',
    'Fiat': 'https://www.cnhindustrial.com/-/media/CNHi/cnhicorporate/Home-Page/CNH_at_Agritechnica2025-TechDayLOGO_new.jpg?h=656&iar=0&w=1053&rev=-1&hash=733F80D55851F2AB23CE2D4F442D492D',
    'fiat': 'https://www.cnhindustrial.com/-/media/CNHi/cnhicorporate/Home-Page/CNH_at_Agritechnica2025-TechDayLOGO_new.jpg?h=656&iar=0&w=1053&rev=-1&hash=733F80D55851F2AB23CE2D4F442D492D',
    'FIAT': 'https://www.cnhindustrial.com/-/media/CNHi/cnhicorporate/Home-Page/CNH_at_Agritechnica2025-TechDayLOGO_new.jpg?h=656&iar=0&w=1053&rev=-1&hash=733F80D55851F2AB23CE2D4F442D492D',
    'Ford': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'ford': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'FORD': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'Fordson': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'fordson': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'FORDSON': 'https://www.ford.com/acslibs/content/dam/na/ford/en_us/images/brand/Ford_OG_1200x630.jpg',
    'Foton': 'https://www.foton.com.cn/./static/images/user.png',
    'foton': 'https://www.foton.com.cn/./static/images/user.png',
    'FOTON': 'https://www.foton.com.cn/./static/images/user.png',
    'Hart-Parr': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'hart-parr': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'HART-PARR': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Hesston': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'hesston': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'HESSTON': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Hinomoto': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'hinomoto': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'HINOMOTO': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'Hitachi': 'https://www.hitachi.com/content/dam/hitachi/common/image/og/og_hitachi_logo.png',
    'hitachi': 'https://www.hitachi.com/content/dam/hitachi/common/image/og/og_hitachi_logo.png',
    'HITACHI': 'https://www.hitachi.com/content/dam/hitachi/common/image/og/og_hitachi_logo.png',
    'JCB': 'https://cdn-ukwest.onetrust.com/logos/static/powered_by_logo.svg',
    'jcb': 'https://cdn-ukwest.onetrust.com/logos/static/powered_by_logo.svg',
    'John Deere': 'https://www.deere.com/assets/images/common/home-page/building-america-since-1837-1366x374.jpg',
    'john deere': 'https://www.deere.com/assets/images/common/home-page/building-america-since-1837-1366x374.jpg',
    'JOHN DEERE': 'https://www.deere.com/assets/images/common/home-page/building-america-since-1837-1366x374.jpg',
    'JohnDeere': 'https://www.deere.com/assets/images/common/home-page/building-america-since-1837-1366x374.jpg',
    'johndeere': 'https://www.deere.com/assets/images/common/home-page/building-america-since-1837-1366x374.jpg',
    'Kioti': 'https://kioti-com.files.svdcdn.com/production/img/usa_logo_emblem_registered_2023_2500px_720.png?dm=1765828176',
    'kioti': 'https://kioti-com.files.svdcdn.com/production/img/usa_logo_emblem_registered_2023_2500px_720.png?dm=1765828176',
    'KIOTI': 'https://kioti-com.files.svdcdn.com/production/img/usa_logo_emblem_registered_2023_2500px_720.png?dm=1765828176',
    'Kubota': 'https://cdn-apac.onetrust.com/logos/static/powered_by_logo.svg',
    'kubota': 'https://cdn-apac.onetrust.com/logos/static/powered_by_logo.svg',
    'KUBOTA': 'https://cdn-apac.onetrust.com/logos/static/powered_by_logo.svg',
    'Lamborghini': 'https://www.same-tractors.com/_nuxt/img/logo_sdf_white.939c86f.png',
    'lamborghini': 'https://www.same-tractors.com/_nuxt/img/logo_sdf_white.939c86f.png',
    'LAMBORGHINI': 'https://www.same-tractors.com/_nuxt/img/logo_sdf_white.939c86f.png',
    'Landini': 'https://www.landini.it/wp-content/uploads/2018/01/landini_logo_web.png',
    'landini': 'https://www.landini.it/wp-content/uploads/2018/01/landini_logo_web.png',
    'LANDINI': 'https://www.landini.it/wp-content/uploads/2018/01/landini_logo_web.png',
    'Lanz': 'https://www.deutz-fahr.com/_nuxt/img/f3b2a84.png',
    'lanz': 'https://www.deutz-fahr.com/_nuxt/img/f3b2a84.png',
    'LANZ': 'https://www.deutz-fahr.com/_nuxt/img/f3b2a84.png',
    'Mercedes-Benz': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'mercedes-benz': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'MERCEDES-BENZ': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'Minneapolis': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'minneapolis': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'MINNEAPOLIS': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Minneapolis-Moline': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'minneapolis-moline': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'MINNEAPOLIS-MOLINE': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Mitsubishi': 'https://cdn-au.onetrust.com/logos/static/poweredBy_ot_logo.svg',
    'mitsubishi': 'https://cdn-au.onetrust.com/logos/static/poweredBy_ot_logo.svg',
    'MITSUBISHI': 'https://cdn-au.onetrust.com/logos/static/poweredBy_ot_logo.svg',
    'Oliver': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'oliver': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'OLIVER': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Pasquali': 'https://www.pasquali.it/themes/at_onsport/assets/img/modules/appagebuilder/images/cdl logo bianco.png',
    'pasquali': 'https://www.pasquali.it/themes/at_onsport/assets/img/modules/appagebuilder/images/cdl logo bianco.png',
    'PASQUALI': 'https://www.pasquali.it/themes/at_onsport/assets/img/modules/appagebuilder/images/cdl logo bianco.png',
    'Porsche': 'https://images.ctfassets.net/1oyzmkwpf3d5/25tp7ukRYP6w7PGBNpTOYU/7a3ec791172f739ca5a7179a0634132f/Red_plaid_bag__black_jacket__red_travel_mug__toy_car__and_keychain_on_a_red_and_gold_background.jpg',
    'porsche': 'https://images.ctfassets.net/1oyzmkwpf3d5/25tp7ukRYP6w7PGBNpTOYU/7a3ec791172f739ca5a7179a0634132f/Red_plaid_bag__black_jacket__red_travel_mug__toy_car__and_keychain_on_a_red_and_gold_background.jpg',
    'PORSCHE': 'https://images.ctfassets.net/1oyzmkwpf3d5/25tp7ukRYP6w7PGBNpTOYU/7a3ec791172f739ca5a7179a0634132f/Red_plaid_bag__black_jacket__red_travel_mug__toy_car__and_keychain_on_a_red_and_gold_background.jpg',
    'Renault': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'renault': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'RENAULT': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'SAME': 'https://www.same-tractors.com/_nuxt/img/logo_sdf_white.939c86f.png',
    'same': 'https://www.same-tractors.com/_nuxt/img/logo_sdf_white.939c86f.png',
    'Satoh': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'satoh': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'SATOH': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'Shibaura': 'https://www.shibaura.com/wp-content/uploads/2023/11/logoWebsite-2.png',
    'shibaura': 'https://www.shibaura.com/wp-content/uploads/2023/11/logoWebsite-2.png',
    'SHIBAURA': 'https://www.shibaura.com/wp-content/uploads/2023/11/logoWebsite-2.png',
    'Solis': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'solis': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'SOLIS': 'https://consent.trustarc.com/get?name=Powered-By-TrustArc.png',
    'Sonalika': 'https://www.sonalika.com/uploaded_files/media_room/sonalika-tractor-logo-1716630288.webp',
    'sonalika': 'https://www.sonalika.com/uploaded_files/media_room/sonalika-tractor-logo-1716630288.webp',
    'SONALIKA': 'https://www.sonalika.com/uploaded_files/media_room/sonalika-tractor-logo-1716630288.webp',
    'Swaraj': 'https://www.swarajtractors.com/sites/default/files/images/Swaraj_Product-963FE_985x590.jpg',
    'swaraj': 'https://www.swarajtractors.com/sites/default/files/images/Swaraj_Product-963FE_985x590.jpg',
    'SWARAJ': 'https://www.swarajtractors.com/sites/default/files/images/Swaraj_Product-963FE_985x590.jpg',
    'TAFE': 'https://www.tafe.com/img/tafe-logo-share.png',
    'tafe': 'https://www.tafe.com/img/tafe-logo-share.png',
    'TYM': 'https://img.atom.com/story_images/visual_images/logo-image-34486-tym.jpg?class=show',
    'tym': 'https://img.atom.com/story_images/visual_images/logo-image-34486-tym.jpg?class=show',
    'Unimog': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'unimog': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'UNIMOG': 'https://www.mercedes-benz.com/logos/mb-star-white.svg',
    'Valmet': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'valmet': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'VALMET': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'Valtra': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'valtra': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'VALTRA': 'https://www.valtra.com/content/dam/Brands/Valtra/agco.png',
    'Versatile': 'https://www.versatile-ag.com/../img/home_nextshow_CPS26.jpg',
    'versatile': 'https://www.versatile-ag.com/../img/home_nextshow_CPS26.jpg',
    'VERSATILE': 'https://www.versatile-ag.com/../img/home_nextshow_CPS26.jpg',
    'Volvo': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'volvo': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'VOLVO': 'https://cdn.cookielaw.org/logos/static/powered_by_logo.svg',
    'White': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'white': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'WHITE': 'https://s7d9.scene7.com/is/image/agco/YTLogo?fmt=png-alpha',
    'Yanmar': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'yanmar': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'YANMAR': 'https://www.yanmar.com/ltc/assets/img/img/dbe44d5a6b/img_site-logo_04.png',
    'Zanello': 'https://zanello.com.ar/wp-content/uploads/2021/12/1-02.png',
    'zanello': 'https://zanello.com.ar/wp-content/uploads/2021/12/1-02.png',
    'ZANELLO': 'https://zanello.com.ar/wp-content/uploads/2021/12/1-02.png',
    'Zetor': 'https://cookies.giant.cz/data/images/0a/zetor-logo-red.240x35.fit.q85.png',
    'zetor': 'https://cookies.giant.cz/data/images/0a/zetor-logo-red.240x35.fit.q85.png',
    'ZETOR': 'https://cookies.giant.cz/data/images/0a/zetor-logo-red.240x35.fit.q85.png',
  };

  return brandMap[brandName] || null;
}

/**
 * Colores de marca para fondos (estilo TractorData.es)
 */
export function getBrandColor(brandName: string): string {
  const colorMap: Record<string, string> = {
    'John Deere': 'bg-[#367C2B]', // Verde John Deere
    'john deere': 'bg-[#367C2B]',
    'Kubota': 'bg-[#FF6600]', // Naranja Kubota
    'kubota': 'bg-[#FF6600]',
    'New Holland': 'bg-[#003087]', // Azul New Holland
    'new holland': 'bg-[#003087]',
    'Case IH': 'bg-[#FF0000]', // Rojo Case IH
    'case ih': 'bg-[#FF0000]',
    'Case': 'bg-[#FF0000]',
    'case': 'bg-[#FF0000]',
    'Massey Ferguson': 'bg-[#DC143C]', // Rojo Massey Ferguson
    'massey ferguson': 'bg-[#DC143C]',
    'Fendt': 'bg-[#00A859]', // Verde Fendt
    'fendt': 'bg-[#00A859]',
    'Claas': 'bg-[#6DB644]', // Verde lima Claas
    'claas': 'bg-[#6DB644]',
    'Deutz-Fahr': 'bg-[#1E3A8A]', // Azul oscuro
    'deutz-fahr': 'bg-[#1E3A8A]',
    'Valtra': 'bg-[#7C3AED]', // Púrpura
    'valtra': 'bg-[#7C3AED]',
    'Landini': 'bg-[#3B82F6]', // Azul claro
    'landini': 'bg-[#3B82F6]',
    'Solis': 'bg-[#2563EB]', // Azul
    'solis': 'bg-[#2563EB]',
    'McCormick': 'bg-[#DC2626]', // Rojo
    'mccormick': 'bg-[#DC2626]',
  };

  return colorMap[brandName] || 'bg-gray-600'; // Color por defecto
}

