/**
 * Pre-built intro paragraph texts keyed by tractor slug.
 * Generated by `npm run build:narratives` (scripts/buildNarratives.ts).
 * If a slug is missing, TractorIntroParagraph falls back to runtime generation.
 */
import introsData from './intros.json';

export interface IntroEntry {
  en: string;
  es: string;
}

export const introsMap: Record<string, IntroEntry> = introsData as Record<string, IntroEntry>;
