/**
 * Precomputed tractor narratives (generated by scripts/buildNarratives.ts).
 * Run before build: npm run build:narratives (or use prebuild).
 */
import type { TractorNarrative } from '@/lib/tractorNarrative';
import narrativesData from './narratives.json';

export const narrativesMap: Record<string, TractorNarrative> =
  (narrativesData as Record<string, TractorNarrative>) ?? {};
