/**
 * Tractors with optional Wikimedia Commons images (generated by scripts/fetchTractorImages.ts).
 * Merges processed-tractors with data/tractor-images.json. Do not edit by hand.
 */
import { scrapedTractors } from './processed-tractors';
import tractorImages from './tractor-images.json';

const images = tractorImages as Record<string, import('@/types/tractor').TractorImage>;

export const scrapedTractorsWithImages = scrapedTractors.map((t) => ({
  ...t,
  image: images[t.slug] ?? undefined,
  imageUrl: images[t.slug]?.url ?? t.imageUrl,
}));
